FROM ubuntu:latest 

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update \
 && apt-get -yq install --no-install-recommends \
    build-essential \
    ca-certificates \
    libnuma-dev \
    python3-pip \
    python3-pyelftools \
    python3-setuptools \
    wget \
	curl \
	git \
	libgoogle-perftools-dev \
	python2.7 \
	python3-minimal \
	clang \
    llvm \
    llvm-dev \
    libelf-dev \
    libpcap-dev \
    gcc-multilib \
    build-essential \
    linux-headers-generic \
    linux-tools-common \
    linux-tools-generic \
    tcpdump \
    libbfd-dev \
    libcap-dev \
    cmake \
    libbsd-dev \
    libedit-dev 


WORKDIR /ebpf-equivalence

RUN git clone https://github.com/sebymiano/ebpf-equivalence-check.git --recurse-submodules

RUN mv ebpf-equivalence-check/bpf-equivalence-check/* .
RUN rm -rf ebpf-equivalence-check

RUN make -C src

ENTRYPOINT ["/ebpf-equivalence/src/equivalence_check"]