FROM ubuntu:latest 

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update \
 && apt-get -yq install --no-install-recommends \
    build-essential \
    ca-certificates \
    libnuma-dev \
    python3-pip \
    python3-pyelftools \
    python3-setuptools \
    wget \
	curl \
	git \
	libgoogle-perftools-dev \
	python2.7 \
	python3-minimal \
	clang \
    llvm \
    llvm-dev \
    libelf-dev \
    libpcap-dev \
    gcc-multilib \
    build-essential \
    linux-headers-generic \
    linux-tools-common \
    linux-tools-generic \
    tcpdump \
    libbfd-dev \
    libcap-dev \
    cmake \
    libbsd-dev \
    libedit-dev 

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

WORKDIR /

RUN git clone https://github.com/sebymiano/ebpf-equivalence-check.git --recurse-submodules

RUN make -C ebpf-equivalence-check/bpf-equivalence-check/src
RUN cp ebpf-equivalence-check/bpf-equivalence-check/src/equivalence_check /usr/bin
RUN rm -rf ebpf-equivalence-check

ENTRYPOINT ["/usr/bin/equivalence_check"]